    
server:
  port: 8090

spring:
  application:
    name: timesheet
  datasource:
    url: jdbc:mysql://localhost:3306/timesheet
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
        
